# Generated by Django 4.1 on 2023-02-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('surname', models.TextField(null=True)),
                ('email', models.TextField()),
                ('username', models.TextField(null=True)),
                ('password', models.TextField()),
                ('avatar', models.TextField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_App.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.TextField()),
                ('version', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cores', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ram', models.DecimalField(decimal_places=2, max_digits=8)),
                ('storage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_App.user')),
            ],
        ),
    ]
