# Generated by Django 4.2 on 2023-04-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0004_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='docker_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.TextField(default='0.0.0.0', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
