# Generated by Django 4.2 on 2023-04-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0006_rename_ip_server_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='id_wallet',
            new_name='wallet',
        ),
    ]
