# Generated by Django 4.2 on 2023-06-05 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0007_rename_id_user_server_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_App.server')),
            ],
        ),
    ]
