# Generated by Django 4.2 on 2023-06-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0008_consolemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='address',
            field=models.TextField(default='localhost', null=True),
        ),
    ]
