# Generated by Django 4.2 on 2023-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0009_alter_server_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.TextField(default='Sopped'),
        ),
    ]
