# Generated by Django 4.2 on 2023-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0010_server_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.TextField(default='Stopped'),
        ),
    ]
