# Generated by Django 4.2 on 2023-08-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0016_server_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
