# Generated by Django 4.2 on 2023-08-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0022_remove_server_sino'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsoleMessage',
        ),
    ]
