# Generated by Django 4.2 on 2023-08-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0023_delete_consolemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
